import { CanvasLogo } from "@/components/canvas-logo";
import { Link, createRoute } from "@tanstack/react-router";
import { rootRoute } from "./__root";

export const termsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/terms",
  component: TermsPage,
});

function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-10">
      <div className="mb-8 flex items-center gap-3">
        <CanvasLogo size={40} />
        <Link to="/" className="text-foreground text-sm font-semibold">
          Canvas
        </Link>
      </div>

      <div className="prose prose-sm dark:prose-invert max-w-none" data-testid="terms-page">
        <h1>Terms of Service</h1>
        <p className="text-muted-foreground text-xs">Last updated: 2026-07-29</p>

        <p className="rounded-md border border-dashed p-3 text-xs">
          <strong>Draft notice:</strong> this is a template describing how the Service works — it
          has not been reviewed by a lawyer. Review it with qualified legal counsel, and fill in the
          governing-law clause below, before relying on it as a binding agreement.
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By creating an account or using Canvas ("the Service"), you agree to these Terms of
          Service and the accompanying <Link to="/privacy">Privacy Policy</Link>.
        </p>

        <h2>2. The Service</h2>
        <p>
          Canvas is a work-management platform with AI-assisted image generation, chat, and
          copywriting features, organized into workspaces shared by teams.
        </p>

        <h2>3. Accounts</h2>
        <p>
          You're responsible for maintaining the confidentiality of your login credentials and for
          all activity under your account. Notify your workspace admin promptly if you suspect
          unauthorized access.
        </p>

        <h2>4. Acceptable Use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>
            Upload or generate content that is illegal, infringing, or violates a third party's
            rights.
          </li>
          <li>
            Attempt to circumvent usage limits, security controls, or access data outside your
            assigned workspace(s).
          </li>
          <li>
            Generate content that violates the acceptable-use policies of the underlying AI
            providers (OpenAI, Anthropic, Google).
          </li>
        </ul>

        <h2>5. AI-Generated Content</h2>
        <p>
          Content generated by the Service's AI features (images, chat replies, ad copy) is produced
          by third-party AI models and may be inaccurate, low-quality, or unsuitable for its
          intended purpose. You are responsible for reviewing AI-generated content before relying on
          or publishing it. The Service makes no warranty as to the accuracy, originality, or
          fitness of AI-generated output.
        </p>

        <h2>6. Your Content</h2>
        <p>
          You retain ownership of the content you upload or create. By using the Service, you grant
          its operators a license to store, process, and display that content as necessary to
          provide the Service, including sending it to AI providers as described in the Privacy
          Policy.
        </p>

        <h2>7. Third-Party Services</h2>
        <p>
          Integrations with Slack, GitHub, Google Drive, and similar services are subject to those
          services' own terms. The Service is not responsible for the availability or behavior of
          third-party services.
        </p>

        <h2>8. Termination</h2>
        <p>
          A workspace owner/admin may remove your access to a workspace at any time. You may stop
          using the Service and request account deletion at any time.
        </p>

        <h2>9. Disclaimer of Warranties</h2>
        <p>The Service is provided "as is" without warranties of any kind, express or implied.</p>

        <h2>10. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, the operators of the Service are not liable for
          indirect, incidental, or consequential damages arising from your use of the Service.
        </p>

        <h2>11. Changes</h2>
        <p>
          These terms may be updated from time to time; continued use of the Service after a change
          constitutes acceptance.
        </p>

        <h2>12. Governing Law</h2>
        <p>
          <em>
            [Not yet specified — the governing jurisdiction depends on where the operating
            organization is based. Fill in with legal counsel.]
          </em>
        </p>

        <h2>13. Contact</h2>
        <p>
          Questions about these terms should be directed to your workspace administrator or the
          organization operating this deployment.
        </p>
      </div>
    </main>
  );
}
